<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Midas Content Management Framework
on 2012-09-27 19:00:27 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of 'Article' documents,
then the 'ArticleDocument' (skeleton) class probally might be a good place to look. */

namespace CMF\Runtime\Domain\Article;

/**
 * Serves as the base class to the 'Article' document skeleton.
 */
abstract class BaseArticleDocument extends \CMF\Core\Runtime\Document\Document
{ 
    /**
     * Returns an 'Article' document's title.
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->getValue('title');
    }

    /**
     * Sets an 'Article' document's title.
     *
     * @param string $title
     */
    public function setTitle($title)
    {
        $this->setValue('title', $title);
    }

    /**
     * Returns an 'Article' document's subtitle.
     *
     * @return string
     */
    public function getSubtitle()
    {
        return $this->getValue('subtitle');
    }

    /**
     * Sets an 'Article' document's subtitle.
     *
     * @param string $subtitle
     */
    public function setSubtitle($subtitle)
    {
        $this->setValue('subtitle', $subtitle);
    }

    /**
     * Returns an 'Article' document's kicker.
     *
     * @return string
     */
    public function getKicker()
    {
        return $this->getValue('kicker');
    }

    /**
     * Sets an 'Article' document's kicker.
     *
     * @param string $kicker
     */
    public function setKicker($kicker)
    {
        $this->setValue('kicker', $kicker);
    }

    /**
     * Returns an 'Article' document's content.
     *
     * @return string
     */
    public function getContent()
    {
        return $this->getValue('content');
    }

    /**
     * Sets an 'Article' document's content.
     *
     * @param string $content
     */
    public function setContent($content)
    {
        $this->setValue('content', $content);
    }
}
