<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Midas Content Management Framework
on 2012-09-27 19:00:27 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of the 'Article' module,
then the 'ArticleModule' (skeleton) class probally might be a good place to look. */

namespace CMF\Runtime\Domain\Article;

/**
 * Serves as the base class to the 'Article'' module skeleton.
 */
abstract class BaseArticleModule extends \CMF\Core\Runtime\Module\RootModule
{
    /**
     * Creates a new BaseArticleModule instance.
     */
    protected function __construct()
    {
        return parent::__construct('Article', array( 
            \CMF\Core\Runtime\Field\TextField::create('title'), 
            \CMF\Core\Runtime\Field\TextField::create('subtitle'), 
            \CMF\Core\Runtime\Field\TextField::create('kicker'), 
            \CMF\Core\Runtime\Field\TextField::create('content', array( 
                'min' => '100', 
            )),         
        ));
    }

    /**
     * Returns the IDocument implementor to use when creating new documents.
     *
     * @return string Fully qualified name of an IDocument implementation.
     */
    protected function getDocumentImplementor()
    {
        return 'CMF\Runtime\Domain\Article\ArticleDocument';
    }
}
