<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-07-22 00:46:59 and allows to alter the behaviour of the 'SimpleSchema' module.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Example\Domain\SimpleSchema;

use Example\Domain\SimpleSchema\Base;

/**
 * The SimpleSchemaModule class reflects the declared structure of the 'SimpleSchema' entity.
 * It holds the meta data necessary to manage/initiate 'SimpleSchemaDocument' lifecycles.
 */
class SimpleSchemaModule extends Base\SimpleSchemaModule
{

}
