<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-07-22 00:46:59 and allows to alter the behaviour of 'VotingStats' documents.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Example\Domain\SimpleSchema;

use Example\Domain\SimpleSchema\Base;

/**
 * Aggregates information on the number of votes, a max(global) score and average voting.
 */
class VotingStatsDocument extends Base\VotingStatsDocument
{

}
