<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Midas Content Management Framework
on 2012-09-28 16:53:52 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of 'Foo' documents,
then the 'FooDocument' (skeleton) class probally might be a good place to look. */

namespace CMF\Runtime\Domain\Foo;

/**
 * Serves as the base class to the 'Foo' document skeleton.
 */
abstract class BaseFooDocument extends \CMF\Core\Runtime\Document\Document
{ 
    /**
     * Returns an 'Foo' document's title.
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->getValue('title');
    }

    /**
     * Sets an 'Foo' document's title.
     *
     * @param string $title
     */
    public function setTitle($title)
    {
        $this->setValue('title', $title);
    }

    /**
     * Returns an 'Foo' document's description.
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->getValue('description');
    }

    /**
     * Sets an 'Foo' document's description.
     *
     * @param string $description
     */
    public function setDescription($description)
    {
        $this->setValue('description', $description);
    }

    /**
     * Returns an 'Foo' document's bar.
     *
     * @return BarModule
     */
    public function getBar()
    {
        return $this->getValue('bar');
    }

    /**
     * Sets an 'Foo' document's bar.
     *
     * @param BarModule $bar
     */
    public function setBar($bar)
    {
        $this->setValue('bar', $bar);
    }
}
