<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Midas Content Management Framework
on 2012-09-28 13:52:05 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of the 'Foo' module,
then the 'FooModule' (skeleton) class probally might be a good place to look. */

namespace CMF\Runtime\Domain\Foo;

/**
 * Serves as the base class to the 'Foo'' module skeleton.
 */
abstract class BaseFooModule extends \CMF\Core\Runtime\Module\RootModule
{
    /**
     * Creates a new BaseFooModule instance.
     */
    protected function __construct()
    {
        return parent::__construct('Foo', array( 
            \CMF\Core\Runtime\Field\TextField::create('title'), 
            \CMF\Core\Runtime\Field\TextField::create('description'), 
            \CMF\Core\Runtime\Field\AggregateField::create('bar', array(                                 
                'aggregate_module' => 'CMF\\Runtime\\Domain\\Foo\\BarModule',  
            )),         
        ));
    }

    /**
     * Returns the IDocument implementor to use when creating new documents.
     *
     * @return string Fully qualified name of an IDocument implementation.
     */
    protected function getDocumentImplementor()
    {
        return 'CMF\Runtime\Domain\Foo\FooDocument';
    }
}
