<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Midas Content Management Framework
on 2012-09-28 13:52:05 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of 'Bar' documents,
then the 'BarDocument' (skeleton) class probally might be a good place to look. */

namespace CMF\Runtime\Domain\Foo;

/**
 * Serves as the base class to the 'Bar' document skeleton.
 */
abstract class BaseBarDocument extends \CMF\Core\Runtime\Document\Document
{ 
    /**
     * Returns an 'Bar' document's food.
     *
     * @return string
     */
    public function getFood()
    {
        return $this->getValue('food');
    }

    /**
     * Sets an 'Bar' document's food.
     *
     * @param string $food
     */
    public function setFood($food)
    {
        $this->setValue('food', $food);
    }

    /**
     * Returns an 'Bar' document's clickCount.
     *
     * @return int
     */
    public function getClickcount()
    {
        return $this->getValue('clickCount');
    }

    /**
     * Sets an 'Bar' document's clickCount.
     *
     * @param int $clickCount
     */
    public function setClickcount($clickCount)
    {
        $this->setValue('clickCount', $clickCount);
    }
}
