<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Midas Content Management Framework
on 2012-09-27 19:00:27 and allows to alter the behaviour of the 'Article' module.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace CMF\Runtime\Domain\Article;

/**
 * The ArticleModule class reflects the declared structure of the 'Article' entity.
 * It holds the meta data necessary to manage/initiate 'ArticleDocument' lifecycles.
 */
class ArticleModule extends BaseArticleModule
{
    
}
