<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Midas Content Management Framework
on 2012-09-27 19:00:27 and allows to alter the behaviour of 'Article' documents.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace CMF\Runtime\Domain\Article;

/**
 * Articles are made out of textual content and images and may define a location they relate to.
 * We use them to create news, recommendations and to summarize things such as events.
 */
class ArticleDocument extends BaseArticleDocument
{
    
}
