<?php
###############################
# AUTOGENERATED - DO NOT EDIT #
###############################

namespace CMF\Runtime\Domain\Shofi\Place;

use CMF\Core\Runtime\Module;
use CMF\Core\Runtime\Field;

abstract class BasePlaceModule extends Module\RootModule
{
    /**
     * Create a new module instance.
     */
    protected function __construct()
    {
        return parent::__construct('Place', array(
            Field\AggregateField::create('coreItem', array(
                Field\AggregateField::OPT_AGGREGATE_MODULE => 'CMF\Runtime\Domain\Shofi\Place\CoreItemModule'
            ))
        ));
    }

    protected function getDocumentImplementor()
    {
        return 'CMF\Runtime\Domain\Shofi\Place\PlaceDocument';
    }
}
