<?php
###############################
# AUTOGENERATED - DO NOT EDIT #
###############################

namespace CMF\Runtime\Domain\Shofi\Place;
use CMF\Core\Runtime\Document;

abstract class BaseCoreItemDocument extends Document\Document
{
    public function getFirstname()
    {
        return $this->getValue('firstname');
    }

    public function setFirstname($firstname)
    {
        $this->setValue('firstname', $firstname);
    }

    public function getLastname()
    {
        return $this->getValue('lastname');
    }

    public function setLastName($lastname)
    {
        $this->setValue('lastname', $lastname);
    }

    public function getCompany()
    {
        return $this->getValue('company');
    }

    public function setCompany($company)
    {
        $this->setValue('company', $company);
    }

    public function getLocation()
    {
        return $this->getValue('location');
    }

    public function setLocation($location)
    {
        $this->setValue('location', $location);
    }
}
