<?php
###############################
# AUTOGENERATED - DO NOT EDIT #
###############################

namespace CMF\Runtime\Domain\Shofi\Place;

use CMF\Core\Runtime\Module;
use CMF\Core\Runtime\Field;

abstract class BaseLocationModule extends Module\AggregateModule
{
    /**
     * Create a new module instance.
     */
    protected function __construct()
    {
        return parent::__construct('Location', array(
            Field\TextField::create('street'),
            Field\TextField::create('houseNumber'),
            Field\TextField::create('postalCode'),
            Field\TextField::create('city'),
            Field\TextField::create('district'),
            Field\TextField::create('name')
        ));
    }

    protected function getDocumentImplementor()
    {
        return 'CMF\Runtime\Domain\Shofi\Place\LocationDocument';
    }
}
