<?php
###############################
# AUTOGENERATED - DO NOT EDIT #
###############################

namespace CMF\Runtime\Domain\Shofi\Place;
use CMF\Core\Runtime\Document;

abstract class BasePlaceDocument extends Document\Document
{
    public function getCoreItem()
    {
        return $this->getValue('coreItem');
    }

    public function setCoreItem($coreItem)
    {
        $this->setValue('coreItem');
    }
}
