<?php
###############################
# AUTOGENERATED - DO NOT EDIT #
###############################

namespace CMF\Runtime\Domain\Shofi\Place;

use CMF\Core\Runtime\Module;
use CMF\Core\Runtime\Field;

abstract class BaseCoreItemModule extends Module\AggregateModule
{
    /**
     * Create a new module instance.
     */
    protected function __construct()
    {
        return parent::__construct('CoreItem', array(
            Field\TextField::create('firstname'),
            Field\TextField::create('lastname'),
            Field\TextField::create('company'),
            Field\AggregateField::create('location', array(
                Field\AggregateField::OPT_AGGREGATE_MODULE => 'CMF\Runtime\Domain\Shofi\Place\LocationModule'
            ))
        ));
    }

    protected function getDocumentImplementor()
    {
        return 'CMF\Runtime\Domain\Shofi\Place\CoreItemDocument';
    }
}
