<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Midas Content Management Framework
on 2012-09-28 16:53:52 and allows to alter the behaviour of 'Bar' documents.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace CMF\Runtime\Domain\Foo;

/**
 * The Bar aggregate module reflects bar data and so on ...
 */
class BarDocument extends BaseBarDocument
{
    
}
