<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Midas Content Management Framework
on 2012-09-28 16:53:52 and allows to alter the behaviour of the 'Foo' module.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace CMF\Runtime\Domain\Foo;

/**
 * The FooModule class reflects the declared structure of the 'Foo' entity.
 * It holds the meta data necessary to manage/initiate 'FooDocument' lifecycles.
 */
class FooModule extends BaseFooModule
{
    
}
