<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r) 
on 2013-07-22 22:43:40 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of 'VotingStats' documents,
then the 'VotingStatsDocument' (skeleton) class probally might be a good place to look. */

namespace Example\Domain\SimpleSchema\Base;

use Dat0r\Core\Document;

/**
 * Serves as the base class to the 'VotingStats' document skeleton.
 */
abstract class VotingStatsDocument extends Document\Document
{ 
    /**
     * Returns an 'VotingStats' document's averageScore.
     *
     * @return 
     */
    public function getAveragescore()
    {
        return $this->getValue('averageScore');
    }

    /**
     * Sets an 'VotingStats' document's averageScore.
     *
     * @param  $averageScore
     */
    public function setAveragescore($averageScore)
    {
        $this->setValue('averageScore', $averageScore);
    }

    /**
     * Returns an 'VotingStats' document's globalScore.
     *
     * @return 
     */
    public function getGlobalscore()
    {
        return $this->getValue('globalScore');
    }

    /**
     * Sets an 'VotingStats' document's globalScore.
     *
     * @param  $globalScore
     */
    public function setGlobalscore($globalScore)
    {
        $this->setValue('globalScore', $globalScore);
    }

    /**
     * Returns an 'VotingStats' document's votingCount.
     *
     * @return 
     */
    public function getVotingcount()
    {
        return $this->getValue('votingCount');
    }

    /**
     * Sets an 'VotingStats' document's votingCount.
     *
     * @param  $votingCount
     */
    public function setVotingcount($votingCount)
    {
        $this->setValue('votingCount', $votingCount);
    }
}
