<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-07-22 22:43:40 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of the 'VotingStats' module,
then the 'VotingStatsModule' (skeleton) class probally might be a good place to look. */

namespace Example\Domain\SimpleSchema\Base;

use Dat0r\Core\Module;

/**
 * Serves as the base class to the 'VotingStats'' module skeleton.
 */
abstract class VotingStatsModule extends Module\RootModule
{
    /**
     * Creates a new VotingStatsModule instance.
     */
    protected function __construct()
    {
        parent::__construct('VotingStats', array( 
            Dat0r\Core\Field\IntegerField::create('averageScore', array('precision' => 'float',)), 
            Dat0r\Core\Field\IntegerField::create('globalScore'), 
            Dat0r\Core\Field\IntegerField::create('votingCount'), 
        ));
    }

    /**
     * Returns the IDocument implementor to use when creating new documents.
     *
     * @return string Fully qualified name of an IDocument implementation.
     */
    protected function getDocumentImplementor()
    {
        return 'Example\Domain\SimpleSchema\VotingStatsDocument';
    }
}
