<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r) 
on 2013-07-22 00:46:59 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of 'SimpleSchema' documents,
then the 'SimpleSchemaDocument' (skeleton) class probally might be a good place to look. */

namespace Example\Domain\SimpleSchema\Base;

use Dat0r\Core\Document;

/**
 * Serves as the base class to the 'SimpleSchema' document skeleton.
 */
abstract class SimpleSchemaDocument extends Document\Document
{ 
    /**
     * Returns an 'SimpleSchema' document's title.
     *
     * @return 
     */
    public function getTitle()
    {
        return $this->getValue('title');
    }

    /**
     * Sets an 'SimpleSchema' document's title.
     *
     * @param  $title
     */
    public function setTitle($title)
    {
        $this->setValue('title', $title);
    }

    /**
     * Returns an 'SimpleSchema' document's content.
     *
     * @return 
     */
    public function getContent()
    {
        return $this->getValue('content');
    }

    /**
     * Sets an 'SimpleSchema' document's content.
     *
     * @param  $content
     */
    public function setContent($content)
    {
        $this->setValue('content', $content);
    }

    /**
     * Returns an 'SimpleSchema' document's keywords.
     *
     * @return 
     */
    public function getKeywords()
    {
        return $this->getValue('keywords');
    }

    /**
     * Sets an 'SimpleSchema' document's keywords.
     *
     * @param  $keywords
     */
    public function setKeywords($keywords)
    {
        $this->setValue('keywords', $keywords);
    }

    /**
     * Returns an 'SimpleSchema' document's votingStats.
     *
     * @return 
     */
    public function getVotingstats()
    {
        return $this->getValue('votingStats');
    }

    /**
     * Sets an 'SimpleSchema' document's votingStats.
     *
     * @param  $votingStats
     */
    public function setVotingstats($votingStats)
    {
        $this->setValue('votingStats', $votingStats);
    }
}
