<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-07-22 22:43:40 and allows to alter the behaviour of the 'VotingStats' module.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Example\Domain\SimpleSchema;

use Example\Domain\SimpleSchema\Base;

/**
 * The VotingStatsModule class reflects the declared structure of the 'VotingStats' entity.
 * It holds the meta data necessary to manage/initiate 'VotingStatsDocument' lifecycles.
 */
class VotingStatsModule extends Base\VotingStatsModule
{

}
